CREATE SEQUENCE SEQ_EQUIPMENT START WITH 1 INCREMENT BY 1;

CREATE TABLE EQUIPMENT (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    LOCATION VARCHAR2(100),
    TYPE VARCHAR2(50),
    STATUS VARCHAR2(20) CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    CREATED_AT TIMESTAMP
);

CREATE OR REPLACE TRIGGER TRG_EQUIPMENT_ID
BEFORE INSERT ON EQUIPMENT
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
SELECT SEQ_EQUIPMENT.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
