CREATE SEQUENCE SEQ_MEASUREMENT START WITH 1 INCREMENT BY 1;

CREATE TABLE MEASUREMENT (
    ID NUMBER PRIMARY KEY,
    CONSUMPTION_WH NUMBER(10,2),
    MEASURED_AT TIMESTAMP,
    EQUIPMENT_ID NUMBER NOT NULL,
    CONSTRAINT FK_MEASUREMENT_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID)
        REFERENCES EQUIPMENT(ID)
);

CREATE OR REPLACE TRIGGER TRG_MEASUREMENT_ID
BEFORE INSERT ON MEASUREMENT
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
    SELECT SEQ_MEASUREMENT.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
