CREATE SEQUENCE SEQ_ALERT START WITH 1 INCREMENT BY 1;

CREATE TABLE ALERT (
    ID NUMBER PRIMARY KEY,
    TYPE VARCHAR2(30) CHECK (TYPE IN ('LIMIT_EXCEEDED', 'NO_CONSUMPTION')),
    VALUE NUMBER(10,2),
    OCCURRED_AT TIMESTAMP,
    EQUIPMENT_ID NUMBER NOT NULL,
    CONSTRAINT FK_ALERT_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID)
    REFERENCES EQUIPMENT(ID)
);

CREATE OR REPLACE TRIGGER TRG_ALERT_ID
BEFORE INSERT ON ALERT
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
SELECT SEQ_ALERT.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
