CREATE SEQUENCE SEQ_CORRECTIVE_ACTION START WITH 1 INCREMENT BY 1;

CREATE TABLE CORRECTIVE_ACTION (
    ID NUMBER PRIMARY KEY,
    DESCRIPTION VARCHAR2(255),
    RESPONSIBLE VARCHAR2(100),
    REGISTERED_AT TIMESTAMP,
    ALERT_ID NUMBER UNIQUE,
    CONSTRAINT FK_CORRECTIVE_ACTION_ALERT FOREIGN KEY (ALERT_ID)
        REFERENCES ALERT(ID)
);

CREATE OR REPLACE TRIGGER TRG_CORRECTIVE_ACTION_ID
BEFORE INSERT ON CORRECTIVE_ACTION
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
SELECT SEQ_CORRECTIVE_ACTION.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
