CREATE SEQUENCE SEQ_USER START WITH 1 INCREMENT BY 1;

CREATE TABLE TBL_USER (
    ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(100) NOT NULL UNIQUE,
    EMAIL VARCHAR2(150) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(30) CHECK (ROLE IN ('ADMIN', 'USER', 'MANAGER'))
);

CREATE OR REPLACE TRIGGER TRG_USER_ID
BEFORE INSERT ON TBL_USER
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
SELECT SEQ_USER.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
